### ISSUE TITLE
Include Message Support

### ISSUE THREAD

**Issue by Elitezen** [Elitezen/discord-trivia#5]
Currently the library is Slash Command based. However, a large portion of the Discord.JS user base still uses messages to run commands. 

I would like `TriviaManager` along with `TriviaGame` to support accepting messages as well as Command Interactions.

**Comment by Turtlepaw** [comment]
Hmm, I don't really see the point in this as message intent is being removed... And they should just use interaction commands.

**Comment by Elitezen** [comment]
Message is actually become a privledged intent in April. Larger bots will have to request the intent. However, that still leaves our target audience which is small bot developers. 

There is still a significant amount of users who use messages, just a thought. I think we'll need to wait and see if any request it

**Comment by Turtlepaw** [comment]
Ok, well I'm going to close this issue for now

**Comment by Turtlepaw** [comment]
This update should also include context menus.
